name: Bot validation

on:
  push:
    paths:
      - 'caltechdata_api/cli.py'
      - 'caltechdata_api/customize_schema.py'
      - 'caltechdata_api/caltechdata_write.py'
      - 'caltechdata_api/caltechdata_edit.py' 
      - 'README.md'
  pull_request:
    paths:
      - 'caltechdata_api/cli.py'
      - 'caltechdata_api/customize_schema.py'
      - 'caltechdata_api/caltechdata_write.py'
      - 'caltechdata_api/caltechdata_edit.py' 
      - 'README.md'

jobs:
  validate-metadata:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests s3fs cryptography 
        pip install .

    - name: Run against CaltechData Test system
      env:
        RDMTOK: ${{ secrets.CALTECHDATA_TOKEN }}
      run: |
        cd tests
        pytest test_unit.py
        pytest test_rdm.py
    - name: Run Medata Validation Test and RDM
      env:
        RDMTOK: ${{ secrets.CALTECHDATA_TOKEN }}
      run: |
        cd tests
        python bot_yaml.py
        
