name: Bot validation

on:
  push:
    paths:
      - 'caltechdata_api/cli.py'
      - 'caltechdata_api/customize_schema.py'
      - 'caltechdata_api/caltechdata_write.py'
      - 'caltechdata_api/caltechdata_edit.py' 
      - 'README.md'
  pull_request:
    paths:
      - 'caltechdata_api/cli.py'
      - 'caltechdata_api/customize_schema.py'
      - 'caltechdata_api/caltechdata_write.py'
      - 'caltechdata_api/caltechdata_edit.py' 
      - 'README.md'

jobs:
  validate-metadata:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Check for Required Environment Variables
      env:
        CALTECHDATA_TOKEN: ${{ secrets.CALTECHDATA_TOKEN }}
      run: |
        if [ -z "$CALTECHDATA_TOKEN" ]; then
          echo "Error: CALTECHDATA_TOKEN environment variable is not set"
          exit 1
        fi
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests s3fs cryptography 
        pip install .

    - name: Run CaltechDATA Metadata Validation
      env:
        CALTECHDATA_TOKEN: ${{ secrets.CALTECHDATA_TOKEN }}
      run: |
        python tests/bot_yaml.py
    - name: Run Unit Tests
      run: |
        cd tests
        pytest test_unit.py
        pytest test_rdm.py
