name: Validate CaltechDATA Metadata Integrity

on:
  push:
    paths:
      - 'caltechdata_api/cli.py'
      - 'README.md'
  pull_request:
    paths:
      - 'caltechdata_api/cli.py'
      - 'README.md'

jobs:
  validate-metadata:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Check for Required Environment Variables
      env:
        CALTECHDATA_TOKEN: ${{ secrets.CALTECHDATA_TOKEN }}
      run: |
        if [ -z "$CALTECHDATA_TOKEN" ]; then
          echo "Error: CALTECHDATA_TOKEN environment variable is not set"
          exit 1
        fi
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests s3fs cryptography caltechdata_api
    
    - name: Validate README Documentation
      run: |
        if ! grep -q "# CaltechDATA CLI" README.md; then
          echo "Error: README.md is missing the main project title section"
          exit 1
        fi
        if ! grep -q "## Installation" README.md; then
          echo "Error: README.md is missing the Installation section"
          exit 1
        fi
        if ! grep -q "## Usage" README.md; then
          echo "Error: README.md is missing the Usage section"
          exit 1
        fi
        echo "README.md documentation validation passed"
    
    - name: Run CaltechDATA Metadata Validation
      env:
        CALTECHDATA_TOKEN: ${{ secrets.CALTECHDATA_TOKEN }}
      run: |
        python tests/bot_yaml.py
