name: Publish

on:
  push:
    tags:
      - v*

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.14"
      - name: Build package
        run: uv build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.14.2
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
