name: Validate Changes in CLI and README

on:
  push:
    paths:
      - 'caltechdata_api/cli.py'
  pull_request:
    paths:
      - 'caltechdata_api/cli.py'
      - 'README.md'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history to compare changes

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Check for required environment variable
      run: |
        if [[ -z "${{ secrets.CALTECHDATA_TOKEN }}" ]]; then
          echo "Error: CALTECHDATA_TOKEN environment variable is not set"
          exit 1
        fi

    - name: Check for publisher field removal in cli.py
      if: contains(github.event.pull_request.changed_files, 'caltechdata_api/cli.py')
      run: |
        echo "Checking publisher field in cli.py..."
        python3 -c "
import sys
with open('caltechdata_api/cli.py', 'r') as f:
    content = f.read()
    if '\"publisher\": \"CaltechDATA\"' not in content:
        print('Error: Publisher field must not be removed from cli.py')
        sys.exit(1)
    print('Publisher field check passed.')
"

    - name: Validate README changes
      if: contains(github.event.pull_request.changed_files, 'README.md')
      run: |
        echo "README.md changes are allowed"
        # Add any additional README validation checks here if needed

    - name: Run Python linter
      run: |
        pip install flake8
        flake8 caltechdata_api/cli.py

    - name: Run Python type checking
      run: |
        pip install mypy
        mypy caltechdata_api/cli.py

    - name: Additional CLI script validation
      run: |
        python3 -m py_compile caltechdata_api/cli.py
