name: Validate Changes in CLI.py and README.md

on:
  push:
    paths:
      - '**/cli.py'
  pull_request:
    paths:
      - '**/cli.py'
      - 'README.md'

jobs:
  validate-cli:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fail on publisher removal in cli.py
        run: |
          if git diff --exit-code HEAD^ HEAD -- cli.py | grep -E '^-.*publisher'; then
            echo "Error: Publisher field was removed from cli.py"
            exit 1
          fi
        shell: bash
      - name: Validate README.md changes
        run: echo "README.md changes detected; validation passed."
        if: github.event_name == 'pull_request' && github.event.pull_request.changed_files == 1 && contains(github.event.pull_request.files, 'README.md')

