name: Validate Metadata Template Changes
on:
  push:
    paths:
      - 'caltechdata_api/cli.py'
  pull_request:
    paths:
      - 'caltechdata_api/cli.py'
      - 'README.md'

jobs:
  validate-metadata:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Check for required environment variable
      run: |
        if [[ -z "${{ secrets.CALTECHDATA_TOKEN }}" ]]; then
          echo "Error: CALTECHDATA_TOKEN environment variable is not set"
          exit 1
        fi

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml

    - name: Validate metadata template fields
      run: |
        cat > validate_metadata.py << 'EOF'
        import sys
        import re
        
        def check_metadata_fields(diff_content):
            required_fields = {
                '"titles"': '[{"title": args["title"]}]',
                '"descriptions"': '[{"description": args["description"], "descriptionType": "Abstract"}]',
                '"publishers"': '"CaltechDATA"',
                '"creators"': '[{"affiliation": [{"affiliationIdentifier": affiliation_identifier,"affiliationIdentifierScheme": affiliationIdentifierScheme,"name": name}],"familyName": family_name,"givenName": given_name,"name": f"{family_name}, {given_name}","nameIdentifiers": [{"nameIdentifier": args["orcid"],"nameIdentifierScheme": "ORCID"}],"nameType": "Personal"}]',
                '"types"': '{"resourceType": "", "resourceTypeGeneral": "Dataset"}',
                '"rightsList"': '[args["license"]]',
                '"fundingReferences"': 'args["fundingReferences"]',
                '"schemaVersion"': '"http://datacite.org/schema/kernel-4"',
                '"affiliation"': '[{"affiliationIdentifier": affiliation_identifier,"affiliationIdentifierScheme": affiliationIdentifierScheme,"name": name}]',
                '"nameIdentifiers"': '[{"nameIdentifier": args["orcid"],"nameIdentifierScheme": "ORCID"}]',
                '"awardNumber"': 'award_number',
                '"awardTitle"': 'award_title', 
                '"funderIdentifier"': 'funder_identifier',
                '"funderIdentifierType"': '"ROR"',
                '"funderName"': 'name'
            }
            
            errors = []
            
            lines = diff_content.split('\n')
            for line in lines:
                if line.startswith('-'):
                    for field, expected_value in required_fields.items():
                        if field in line:
                            if expected_value is None:
                                errors.append(f"Error: Required field {field} cannot be removed")
                            elif expected_value not in line:
                                errors.append(f"Error: Required field {field} must maintain value {expected_value}")
            
            return errors
        
        diff_content = sys.stdin.read()
        errors = check_metadata_fields(diff_content)
        
        if errors:
            print("\n".join(errors))
            sys.exit(1)
        else:
            print("Metadata template validation passed")
            sys.exit(0)
        EOF
        
        git diff origin/${{ github.base_ref }} -- caltechdata_api/cli.py | python validate_metadata.py
        
    - name: Allow README changes
      if: contains(github.event.pull_request.changed_files, 'README.md')
      run: |
        echo "README.md changes are allowed"
        exit 0
