name: Validate Changes in CLI.py and README.md

on:
  push:
    paths:
      - 'caltechdata_api/cli.py'
  pull_request:
    paths:
      - 'caltechdata_api/cli.py'
      - 'README.md'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history to compare changes
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Check for required environment variable
      env:
        CALTECHDATA_TOKEN: ${{ secrets.CALTECHDATA_TOKEN }}
      run: |
        if [ -z "$CALTECHDATA_TOKEN" ]; then
          echo "Error: CALTECHDATA_TOKEN environment variable is not set"
          exit 1
        fi

    - name: Check for publisher field in cli.py
      run: |
        # Check if the file was modified
        if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q 'caltechdata_api/cli.py'; then
          # Use grep to check the content of the cli.py file for the publisher field
          if ! grep -q '"publisher": "CaltechDATA"' caltechdata_api/cli.py; then
            echo "Error: The publisher field must be present in cli.py with the value 'CaltechDATA'"
            exit 1
          else
            echo "Publisher field validation passed for cli.py"
          fi
        else
          echo "No changes detected in cli.py"
        fi

    - name: Validate README.md changes
      run: |
        if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q 'README.md'; then
          echo "Performing basic validation on README.md changes"
          # Add your README validation logic here
          echo "README.md validation passed"
        else
          echo "No changes detected in README.md"
        fi
