name: Validate Changes in CLI.py and README.md

on:
  pull_request:
    paths:
      - 'caltechdata_api/cli.py'
      - 'README.md'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensure full history for comparisons

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Check for required environment variable
      run: |
        if [[ -z "${{ secrets.CALTECHDATA_TOKEN }}" ]]; then
          echo "Error: CALTECHDATA_TOKEN environment variable is not set"
          exit 1
        fi

    - name: Check for publisher field removal in cli.py
      run: |
        # Ensure the base branch is fetched
        git fetch origin ${{ github.base_ref }}

        # Check if the publisher field was removed
        if git diff origin/${{ github.base_ref }} -- caltechdata_api/cli.py | grep -q '"publisher":'; then
          echo "Publisher field still exists. Check passed."
        else
          echo "Error: The publisher field must not be removed from cli.py"
          exit 1
        fi

    - name: Allow README changes
      run: |
        if [[ "${{ github.event.pull_request.head.repo.full_name }}" == "README.md" ]]; then
          echo "README.md changes are allowed"
        fi
